{
  version: '3.7',

  services: {
        server: {
        build: {
            context: '.',
            dockerfile: './server/Dockerfile'
        },
        image: 'greycat9515/shop_v2',
        ports: [
            '8080:8080',
        ],
        depends_on: ['db'],
        restart: 'always'
    },
    db: {
        image: 'postgres',
        environment: {
            POSTGRES_DB: 'shop_v2',
            POSTGRES_USER: 'admin',
            POSTGRES_PASSWORD: '4r3r'
        },
        restart: 'always'
    },
    adminer: {
        image: 'adminer',
        ports: ['3000:8080'],
        restart: 'always'
    }
  }
}
